name: ruf
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttertoast: ^3.1.0
  simple_animations: ^1.3.3
  flutter_bloc: ^2.1.1
  url_launcher: 5.5.0

  get:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/c_prog.jpg
    - images/intr_alg.jpg
    - images/info_system.jpg
    - images/cpp.jpg
    - images/dlsd.jpg
    - images/data_str.jpg
    - images/java_prog.jpg
    - images/micro.jpg
    - images/dbms.jpg
    - images/os.jpg
    - images/web.jpg
    - images/archi.jpg
    - images/swe.jpg
    - images/net.jpg
    - images/dss.jpg
    - images/sm.jpg
    - images/viva.jpg
    - images/adalg.jpg
    - images/ce.jpg
    - images/arti.jpg
    - images/gb.jpg
    - images/dm.png

